# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - '*'
pr:
  - '*'

pool:
  vmImage: 'windows-2019'

strategy:
  matrix:
     A:
      VAL1: ON
     B:
      VAL1: OFF
steps:
- powershell: |
    git submodule update --init --recursive
    if (!$?) {
      return Write-Error "git submodule update --init --recursive failed"
    }
    mkdir build
    if (!$?) {
      return Write-Error "mkdir build failed"
    }
    cd build
    if (!$?) {
      return Write-Error "cd build failed"
    }
    $env:CL="/D_WIN32_WINNT#0x0601 /DBOOST_THREAD_VERSION#3"
    $env:BOOST_ROOT=$env:BOOST_ROOT_1_69_0
    $env:PATH="$env:BOOST_ROOT\lib;"+$env:PATH
    cmake -A x64 -DVAL1=OFF ..
    if (!$?) {
      return Write-Error "cmake -A x64 .. failed"
    }
    cmake --build . --config Release
    if (!$?) {
      return Write-Error "cmake --build . --config Release failed"
    }
    cd test
    if (!$?) {
      return Write-Error "cd test failed"
    }
    ctest -VV
    if (!$?) {
      return Write-Error "ctest -VV failed"
    }
  displayName: 'cmake test'
