# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - '*'
pr:
  - '*'

pool:
  vmImage: 'vs2017-win2016'

steps: PowerShell@2
- script: |
    git submodule update --init --recursive
    mkdir build
    cd build
    set CL="/D_WIN32_WINNT#0x0601 /DBOOST_THREAD_VERSION#3"
    set BOOST_ROOT=%BOOST_ROOT_1_69_0%
    set PATH=%BOOST_ROOT%\lib;%PATH%
    cmake -A x64 ..
    echo $?
    cmake --build . --config Release -- -verbosity:minimal
    cd test
    ctest -VV
  displayName: 'cmake test'
