# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - '*'
pr:
  - '*'

pool:
  vmImage: 'vs2017-win2016'

steps:
- powershell: |
    git submodule update --init --recursive |
    && mkdir build
    cd build
    $env:CL="/D_WIN32_WINNT#0x0601 /DBOOST_THREAD_VERSION#3"
    $env:BOOST_ROOT=$env:BOOST_ROOT_1_69_0
    $env:PATH="$env:BOOST_ROOT\lib;"+$env:PATH
    cmake -A x64 ..
    echo $?
    cmake --build . --config Release
    echo $?
    cd test
    ctest -VV
    echo $?
  displayName: 'cmake test'
