# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - '*'
pr:
  - '*'

pool:
  vmImage: 'windows-2019'

strategy:
  matrix:
     A:
      VAL1: ON
     B:
      VAL1: OFF
steps:
- bash: |
    git submodule update --init --recursive
    mkdir build
    cd build
    export CL="/D_WIN32_WINNT#0x0601 /DBOOST_THREAD_VERSION#3"
    export BOOST_ROOT=$env:BOOST_ROOT_1_69_0
    export PATH="${BOOST_ROOT}\lib;$PATH"
    cmake -A x64 -DVAL1=$(VAL1) ..
    cmake --build . --config Release
    cd test
    ctest -VV
  displayName: 'cmake test'
